config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}

  root 'statuses#index'
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable



  def self.find_for_slack_oauth(access_token, params)
    url = 'https://slack.com/api/oauth.access'
    resp =  HTTParty.get(url, query: {client_id: Rails.application.secrets.slack['app_id'], client_secret: Rails.application.secrets.slack['app_secret'], code: params['code']})

    binding.pry()
    if user = User.where(:uid => access_token.info.user_id).first
      user
    else
      User.create!(:uid => access_token.info.user_id, :email =>  access_token.info.email, :password => Devise.friendly_token[0,20])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:yesterday_info, :today_info, :blockers_info, :user_id, :goals_achieved, :date)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  skip_before_filter :authenticate_user!

  def slack
    @user = User.find_for_slack_oauth request.env["omniauth.auth"], params
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end

  # def failure
  #   binding.pry
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a href="https://slack.com/oauth/authorize?scope=bot&client_id=24633606786.24636235505"
        img alt="Add to Slack" height="40" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" width="139"

      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to "Sign in with Slack", user_omniauth_authorize_path(:slack)
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Status Master'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Status Master'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/statuses/_form.html.slim
= simple_form_for(@status) do |f|
  = f.error_notification

  .form-inputs
    = f.input :yesterday_info
    = f.input :goals_achieved
    = f.input :today_info
    = f.input :blockers_info

  .form-actions
    = f.button :submit

app/views/statuses/edit.html.slim
h1 Editing status

== render 'form'

= link_to 'Show', @status
'|
= link_to 'Back', statuses_path

app/views/statuses/index.html.slim
h1 Listing statuses

table
  thead
    tr
      th Yesterday info
      th Today info
      th Blockers info
      th User
      th Goals achieved
      th Date
      th
      th
      th

  tbody
    - @statuses.each do |status|
      tr
        td = status.yesterday_info
        td = status.today_info
        td = status.blockers_info
        td = status.user
        td = status.goals_achieved
        td = status.date
        td = link_to 'Show', status
        td = link_to 'Edit', edit_status_path(status)
        td = link_to 'Destroy', status, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Status', new_status_path

app/views/statuses/new.html.slim
h1 New status

== render 'form'

= link_to 'Back', statuses_path

app/views/statuses/show.html.slim
p#notice = notice

p
  strong Yesterday info:
  = @status.yesterday_info
p
  strong Today info:
  = @status.today_info
p
  strong Blockers info:
  = @status.blockers_info
p
  strong User:
  = @status.user
p
  strong Goals achieved:
  = @status.goals_achieved
p
  strong Date:
  = @status.date

= link_to 'Edit', edit_status_path(@status)
'|
= link_to 'Back', statuses_path